_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: 'training_dir/mask_rcnn_R_50_FPN_1x/model_0002999.pth'
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 4
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: 'training_dir/mask_rcnn_R_50_FPN_1x'
